/* eslint-disable */
/* tslint:disable */
/**
 * AUTO-GENERATED by testurio generate
 * Source: C:\Users\abolshakov\Downloads\MT.openapi.yaml
 * DO NOT EDIT MANUALLY
 *
 * Generated: 2026-05-26T12:52:19.457Z
 */

import {z} from 'zod';

// ===== Zod Schema =====

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * MT
 * REST service for end-to-end testing of MetaTrader 4 and 5 trading server configurations.
 * OpenAPI spec version: 1.0.0
 */
/**
 * Create trader account
 * @summary Create account
 */
export const postV1AccountsBodyBaseCurrencyDefault = `USD`;
export const postV1AccountsBodyManualTradesDefault = false;
export const postV1AccountsBodyLeverageExclusiveMin = 0;


export const PostV1AccountsBody = z.object({
    "baseCurrency": z.string().default(postV1AccountsBodyBaseCurrencyDefault),
    "balance": z.number().optional(),
    "group": z.string().optional(),
    "email": z.string().optional(),
    "password": z.string().describe('Trader password. The password must contain four types of characters: lowercase letters, uppercase letters, digits, and special characters (#, @, !, etc.). For example: 1Ar#pqkj. \nThe minimum password length is 8 characters. The maximum length is 16 characters.'),
    "name": z.string(),
    "manualTrades": z.boolean().default(postV1AccountsBodyManualTradesDefault),
    "leverage": z.number().gt(postV1AccountsBodyLeverageExclusiveMin)
})

export const PostV1AccountsResponse = z.object({
    "login": z.number()
})


/**
 * Get list of all accounts
 * @summary Get accounts
 */
export const GetV1AccountsQueryParams = z.object({
    "group": z.string().optional()
})

export const getV1AccountsResponseAccountsItemBaseCurrencyDefault = `USD`;
export const getV1AccountsResponseAccountsItemLeverageExclusiveMin = 0;


export const GetV1AccountsResponse = z.object({
    "accounts": z.array(z.object({
        "login": z.number(),
        "name": z.string(),
        "baseCurrency": z.string().default(getV1AccountsResponseAccountsItemBaseCurrencyDefault),
        "balance": z.number(),
        "group": z.string(),
        "leverage": z.number().gt(getV1AccountsResponseAccountsItemLeverageExclusiveMin),
        "equity": z.number(),
        "margin": z.number(),
        "freeMargin": z.number(),
        "createdAt": z.string()
    }))
})


/**
 * Delete trader account
 * @summary Delete acccount
 */
export const DeleteV1AccountsAccountIdParams = z.object({
    "account-id": z.number()
})


/**
 * Create symbol
 * @summary Create Symbol
 */
export const PostV1SymbolsBody = z.object({
    "name": z.string(),
    "tickSize": z.number(),
    "minVolume": z.number(),
    "maxVolume": z.number(),
    "stepVolume": z.number(),
    "contractSize": z.number(),
    "priceDigits": z.number(),
    "security": z.string().describe('What group of symbols it shoulds be added to')
})


/**
 * Create symbol
 * @summary Get symbols
 */
export const getV1SymbolsResponseSymbolsItemTickSizeExclusiveMin = 0;

export const getV1SymbolsResponseSymbolsItemMinVolumeExclusiveMin = 0;

export const getV1SymbolsResponseSymbolsItemMaxVolumeExclusiveMin = 0;

export const getV1SymbolsResponseSymbolsItemStepVolumeExclusiveMin = 0;

export const getV1SymbolsResponseSymbolsItemContractSizeExclusiveMin = 0;

export const getV1SymbolsResponseSymbolsItemPriceDigitsMin = 0;


export const GetV1SymbolsResponse = z.object({
    "symbols": z.array(z.object({
        "name": z.string(),
        "tickSize": z.number().gt(getV1SymbolsResponseSymbolsItemTickSizeExclusiveMin),
        "minVolume": z.number().gt(getV1SymbolsResponseSymbolsItemMinVolumeExclusiveMin),
        "maxVolume": z.number().gt(getV1SymbolsResponseSymbolsItemMaxVolumeExclusiveMin),
        "stepVolume": z.number().gt(getV1SymbolsResponseSymbolsItemStepVolumeExclusiveMin),
        "contractSize": z.number().gt(getV1SymbolsResponseSymbolsItemContractSizeExclusiveMin),
        "priceDigits": z.number().min(getV1SymbolsResponseSymbolsItemPriceDigitsMin),
        "security": z.string()
    }))
})


/**
 * Delete symbol
 * @summary Delete symbol
 */
export const DeleteV1SymbolsNameParams = z.object({
    "name": z.string()
})


/**
 * Get current order book seem by trader. Only for MT5.
 * @summary Get order book
 */
export const GetV1PricesCurrentOrderBookQueryParams = z.object({
    "symbol": z.string()
})

export const getV1PricesCurrentOrderBookResponseBookItemPriceExclusiveMin = 0;

export const getV1PricesCurrentOrderBookResponseBookItemVolumeExclusiveMin = 0;


export const GetV1PricesCurrentOrderBookResponse = z.object({
    "book": z.array(z.object({
        "type": z.enum(['BID', 'ASK']),
        "price": z.number().gt(getV1PricesCurrentOrderBookResponseBookItemPriceExclusiveMin),
        "volume": z.number().gt(getV1PricesCurrentOrderBookResponseBookItemVolumeExclusiveMin)
    }))
})


/**
 * Get last price by symbol, trader
 * @summary Get last price
 */
export const GetV1PricesLastQueryParams = z.object({
    "symbol": z.string(),
    "login": z.string().describe('trader login')
})

export const getV1PricesLastResponsePriceBidExclusiveMin = 0;

export const getV1PricesLastResponsePriceAskExclusiveMin = 0;

export const getV1PricesLastResponsePriceVolumeExclusiveMin = 0;


export const GetV1PricesLastResponse = z.object({
    "price": z.object({
        "bid": z.number().gt(getV1PricesLastResponsePriceBidExclusiveMin),
        "ask": z.number().gt(getV1PricesLastResponsePriceAskExclusiveMin),
        "timestamp": z.number(),
        "volume": z.number().gt(getV1PricesLastResponsePriceVolumeExclusiveMin).optional().describe('Do not return if not supported')
    })
})


/**
 * @summary Get historic prics(ticks)
 */
export const GetV1PricesTicksQueryParams = z.object({
    "login": z.string().optional(),
    "symbol": z.string().optional(),
    "fromTimestamp": z.number().optional(),
    "toTimestamp": z.number().optional()
})

export const GetV1PricesTicksResponse = z.object({
    "ticks": z.array(z.object({
        "bid": z.number(),
        "ask": z.number(),
        "volume": z.number(),
        "timestamp": z.number().optional().describe('Timestamp of the tick in Unix time format (seconds since epoch)')
    }))
})


/**
 * Get all orders, pending, finished
 * @summary Get orders
 */
export const GetV1OrdersQueryParams = z.object({
    "fromTimestamp": z.number().optional().describe('Start timestamp in Unix time seconds (required, must be >= 0)'),
    "toTimestamp": z.number().optional().describe('End timestamp in Unix time seconds (optional, 0 for current time, must be >= 0)')
})

export const getV1OrdersResponseOrdersItemRequestedPriceExclusiveMin = 0;

export const getV1OrdersResponseOrdersItemFilledAvgPriceExclusiveMin = 0;

export const getV1OrdersResponseOrdersItemVolumeMin = 0;

export const getV1OrdersResponseOrdersItemFilledVolumeMin = 0;


export const GetV1OrdersResponse = z.object({
    "orders": z.array(z.object({
        "id": z.number(),
        "type": z.enum(['MARKET', 'LIMIT', 'STOP', 'STOP_LOSS', 'TAKE_POFIT']).optional(),
        "side": z.enum(['BUY', 'SELL']),
        "state": z.string().optional(),
        "symbol": z.string().optional(),
        "requestedPrice": z.number().gt(getV1OrdersResponseOrdersItemRequestedPriceExclusiveMin).optional(),
        "filledAvgPrice": z.number().gt(getV1OrdersResponseOrdersItemFilledAvgPriceExclusiveMin).optional(),
        "volume": z.number().min(getV1OrdersResponseOrdersItemVolumeMin).optional(),
        "filledVolume": z.number().min(getV1OrdersResponseOrdersItemFilledVolumeMin).optional(),
        "createdAt": z.iso.datetime({}),
        "comment": z.string().optional()
    }))
})


/**
 * @summary New Order
 */
export const postV1OrdersBodyVolumeExclusiveMin = 0;

export const postV1OrdersBodyStopLossExclusiveMin = 0;

export const postV1OrdersBodyTakeProfitExclusiveMin = 0;


export const PostV1OrdersBody = z.object({
    "symbol": z.string(),
    "volume": z.number().gt(postV1OrdersBodyVolumeExclusiveMin),
    "side": z.enum(['BUY', 'SELL']),
    "type": z.enum(['LIMIT', 'MARKET', 'STOP']),
    "price": z.number().optional(),
    "stopLoss": z.number().gt(postV1OrdersBodyStopLossExclusiveMin).optional(),
    "takeProfit": z.number().gt(postV1OrdersBodyTakeProfitExclusiveMin).optional(),
    "login": z.number()
})

export const PostV1OrdersResponse = z.object({
    "orderId": z.number(),
    "code": z.string(),
    "message": z.string()
})


/**
 * @summary Get order by id
 */
export const GetV1OrdersOrderIdParams = z.object({
    "order-id": z.number()
})

export const getV1OrdersOrderIdResponseRequestedPriceExclusiveMin = 0;

export const getV1OrdersOrderIdResponseFilledAvgPriceExclusiveMin = 0;

export const getV1OrdersOrderIdResponseVolumeMin = 0;

export const getV1OrdersOrderIdResponseFilledVolumeMin = 0;


export const GetV1OrdersOrderIdResponse = z.object({
    "id": z.number().optional(),
    "type": z.enum(['MARKET', 'LIMIT', 'STOP', 'STOP_LOSS', 'TAKE_POFIT']).optional(),
    "side": z.enum(['BUY', 'SELL']),
    "state": z.string().optional(),
    "symbol": z.string().optional(),
    "time": z.string().optional(),
    "requestedPrice": z.number().gt(getV1OrdersOrderIdResponseRequestedPriceExclusiveMin).optional(),
    "filledAvgPrice": z.number().gt(getV1OrdersOrderIdResponseFilledAvgPriceExclusiveMin).optional(),
    "volume": z.number().min(getV1OrdersOrderIdResponseVolumeMin).optional(),
    "filledVolume": z.number().min(getV1OrdersOrderIdResponseFilledVolumeMin).optional(),
    "createdAt": z.iso.datetime({}),
    "comment": z.string().optional()
})


/**
 * Get execution reports
 * @summary Get Executions
 */
export const GetV1ExecutionsQueryParams = z.object({
    "fromTimestamp": z.number().optional().describe('Start timestamp in Unix time seconds (required, must be >= 0)'),
    "toTimestamp": z.number().optional().describe('End timestamp in Unix time seconds (optional, 0 for current time, must be >= 0)'),
    "login": z.number().optional()
})

export const getV1ExecutionsResponseExecutionsItemFilledVolumeMin = 0;


export const GetV1ExecutionsResponse = z.object({
    "executions": z.array(z.object({
        "executionTimestamp": z.iso.datetime({}).describe('Timestamp when the execution occurred'),
        "type": z.enum(['FILL', 'REJECT', 'EXPIRE', 'CANCEL']),
        "filledVolume": z.number().min(getV1ExecutionsResponseExecutionsItemFilledVolumeMin),
        "orderId": z.number()
    }))
})


/**
 * Drop network connection
 * @summary Disable connection
 */
export const PostV1ConnectionClientIdDropParams = z.object({
    "clientId": z.string()
})


/**
 * Enable network connection
 * @summary Reconnect
 */
export const PostV1ConnectionClientIdEnableParams = z.object({
    "clientId": z.string()
})


/**
 * Get start of server
 * @summary Get server state (online, offline)
 */
export const GetV1ServerStateResponse = z.object({
    "state": z.enum(['ONLINE', 'OFFLINE']),
    "clientsOnline": z.array(z.uuid()).describe('List of online connections with cBridge. ')
})


/**
 * Upload and activate a trading server configuration preset.
 * @summary Apply a test preset
 */
export const PostV1PresetApplyBody = z.object({
    "symbols": z.array(z.object({
        "symbol": z.string().describe('Symbol name.'),
        "description": z.string().describe('Symbol description.'),
        "security": z.string().describe('Security identifier.'),
        "currency": z.string().describe('Currency used for this symbol.'),
        "digits": z.number().describe('Number of digits after decimal point.'),
        "trade": z.number().describe('Trade permissions flag.'),
        "spread": z.number().describe('Spread size in points.'),
        "contractSize": z.number().describe('Contract size for one lot.'),
        "bookDepth": z.number().describe('Depth of market book levels.'),
        "lotMin": z.number().describe('Minimum lot size allowed.'),
        "lotMax": z.number().describe('Maximum lot size allowed.'),
        "lotStep": z.number().describe('Step size for lots.'),
        "markupBid": z.number().describe('Bid markup value.'),
        "markupAsk": z.number().describe('Ask markup value.'),
        "sessionsQuotes": z.array(z.array(z.object({
            "open": z.string().describe('Session open time (HH:MM).'),
            "close": z.string().describe('Session close time (HH:MM).')
        }).describe('Quote session time range.')).describe('List of open-close periods for quotes.')).optional().describe('Trading sessions for quote availability.'),
        "sessionsTrades": z.array(z.array(z.object({
            "open": z.string().describe('Session open time (HH:MM).'),
            "close": z.string().describe('Session close time (HH:MM).')
        }).describe('Trade session time range.')).describe('List of open-close periods for trades.')).optional().describe('Trading sessions for trade execution.')
    }).describe('Symbol configuration details.')).describe('List of tradable symbols available on the server.'),
    "groups": z.array(z.object({
        "group": z.string().describe('Group name.'),
        "company": z.string().describe('Company name associated with the group.'),
        "currency": z.string().describe('Base currency for group accounts.'),
        "marginCall": z.number().describe('Margin call level (percent).'),
        "marginStopout": z.number().describe('Stop out level (percent).'),
        "interestrate": z.number().describe('Interest rate applied to balance.'),
        "securities": z.array(z.object({
            "security": z.string().describe('Security identifier.'),
            "lotMin": z.number().describe('Minimum allowed lot size.'),
            "lotMax": z.number().describe('Maximum allowed lot size.'),
            "lotStep": z.number().describe('Lot step size.'),
            "markupBid": z.number().describe('Bid markup value.'),
            "markupAsk": z.number().describe('Ask markup value.')
        }).describe('Security-specific settings for group.')).describe('List of securities available for this group.')
    }).describe('Configuration of a trading group.')).describe('List of trading groups configurations.'),
    "plugins": z.array(z.object({
        "plugin": z.object({
            "name": z.string().describe('Plugin name.'),
            "enable": z.number().describe('Enable flag (1=enabled, 0=disabled).'),
            "params": z.array(z.object({
                "name": z.string().describe('Parameter name.'),
                "value": z.string().describe('Parameter value.')
            }).describe('Key-value pair for plugin parameter.')).describe('List of plugin parameters.')
        }).optional().describe('Plugin configuration object.')
    }).describe('Plugin entry with name and parameters.')).describe('List of server plugins and their configuration.'),
    "gateways": z.array(z.object({
        "gateway": z.object({
            "name": z.string().describe('Gateway name.'),
            "enable": z.number().describe('Enable flag (1=enabled, 0=disabled).'),
            "params": z.array(z.object({
                "name": z.string().describe('Parameter name.'),
                "value": z.string().describe('Parameter value.')
            }).describe('Key-value pair for gateway parameter.')).describe('List of gateway parameters.'),
            "symbols": z.array(z.object({
                "symbol": z.string().describe('Symbol name.'),
                "markupBid": z.number().describe('Bid markup.'),
                "markupAsk": z.number().describe('Ask markup.')
            }).describe('Symbol-level configuration for gateway.')).describe('List of symbols assigned to this gateway.')
        }).optional().describe('Single gateway settings.')
    }).describe('Gateway configuration object.')).describe('List of configured gateways and their parameters.'),
    "feeders": z.array(z.object({
        "feeder": z.object({
            "name": z.string().describe('Feeder name.'),
            "enable": z.number().describe('Enable flag (1=enabled, 0=disabled).')
        }).optional().describe('Feeder configuration details.')
    }).describe('Feeder configuration entry.')).describe('List of market data feeders.'),
    "users": z.array(z.object({
        "user": z.object({
            "login": z.number().describe('User login ID.'),
            "group": z.string().describe('User group name.'),
            "password": z.string().describe('User password.'),
            "enable": z.number().describe('Enable flag (1=enabled, 0=disabled).'),
            "name": z.string().describe('Full name of the user.'),
            "country": z.string().describe('User country.'),
            "zipcode": z.string().describe('ZIP or postal code.'),
            "city": z.string().describe('City of residence.'),
            "address": z.string().describe('Street address.'),
            "phone": z.string().describe('Phone number.'),
            "email": z.string().describe('Email address.'),
            "balance": z.number().describe('Account balance.'),
            "credit": z.number().describe('Credit amount.'),
            "leverage": z.number().describe('Account leverage ratio.')
        }).optional().describe('User account data.')
    }).describe('User account configuration entry.')).describe('List of user account configurations.')
}).describe('Test preset configuration')

export const PostV1PresetApplyResponse = z.object({
    "errors": z.array(z.object({
        "type": z.string().describe('Object type (sybmol, group, user, etc)'),
        "id": z.string().describe('Object id'),
        "message": z.string().describe('Error message')
    })).optional().describe('Errors list')
})


/**
 * Retrieve the current preset state.
 * @summary Get current preset
 */
export const GetV1PresetCurrentResponse = z.object({
    "symbols": z.array(z.object({
        "symbol": z.string().describe('Symbol name.'),
        "description": z.string().describe('Symbol description.'),
        "security": z.string().describe('Security identifier.'),
        "currency": z.string().describe('Currency used for this symbol.'),
        "digits": z.number().describe('Number of digits after decimal point.'),
        "trade": z.number().describe('Trade permissions flag.'),
        "spread": z.number().describe('Spread size in points.'),
        "contractSize": z.number().describe('Contract size for one lot.'),
        "bookDepth": z.number().describe('Depth of market book levels.'),
        "lotMin": z.number().describe('Minimum lot size allowed.'),
        "lotMax": z.number().describe('Maximum lot size allowed.'),
        "lotStep": z.number().describe('Step size for lots.'),
        "markupBid": z.number().describe('Bid markup value.'),
        "markupAsk": z.number().describe('Ask markup value.'),
        "sessionsQuotes": z.array(z.array(z.object({
            "open": z.string().describe('Session open time (HH:MM).'),
            "close": z.string().describe('Session close time (HH:MM).')
        }).describe('Quote session time range.')).describe('List of open-close periods for quotes.')).optional().describe('Trading sessions for quote availability.'),
        "sessionsTrades": z.array(z.array(z.object({
            "open": z.string().describe('Session open time (HH:MM).'),
            "close": z.string().describe('Session close time (HH:MM).')
        }).describe('Trade session time range.')).describe('List of open-close periods for trades.')).optional().describe('Trading sessions for trade execution.')
    }).describe('Symbol configuration details.')).describe('List of tradable symbols available on the server.'),
    "groups": z.array(z.object({
        "group": z.string().describe('Group name.'),
        "company": z.string().describe('Company name associated with the group.'),
        "currency": z.string().describe('Base currency for group accounts.'),
        "marginCall": z.number().describe('Margin call level (percent).'),
        "marginStopout": z.number().describe('Stop out level (percent).'),
        "interestrate": z.number().describe('Interest rate applied to balance.'),
        "securities": z.array(z.object({
            "security": z.string().describe('Security identifier.'),
            "lotMin": z.number().describe('Minimum allowed lot size.'),
            "lotMax": z.number().describe('Maximum allowed lot size.'),
            "lotStep": z.number().describe('Lot step size.'),
            "markupBid": z.number().describe('Bid markup value.'),
            "markupAsk": z.number().describe('Ask markup value.')
        }).describe('Security-specific settings for group.')).describe('List of securities available for this group.')
    }).describe('Configuration of a trading group.')).describe('List of trading groups configurations.'),
    "plugins": z.array(z.object({
        "plugin": z.object({
            "name": z.string().describe('Plugin name.'),
            "enable": z.number().describe('Enable flag (1=enabled, 0=disabled).'),
            "params": z.array(z.object({
                "name": z.string().describe('Parameter name.'),
                "value": z.string().describe('Parameter value.')
            }).describe('Key-value pair for plugin parameter.')).describe('List of plugin parameters.')
        }).optional().describe('Plugin configuration object.')
    }).describe('Plugin entry with name and parameters.')).describe('List of server plugins and their configuration.'),
    "gateways": z.array(z.object({
        "gateway": z.object({
            "name": z.string().describe('Gateway name.'),
            "enable": z.number().describe('Enable flag (1=enabled, 0=disabled).'),
            "params": z.array(z.object({
                "name": z.string().describe('Parameter name.'),
                "value": z.string().describe('Parameter value.')
            }).describe('Key-value pair for gateway parameter.')).describe('List of gateway parameters.'),
            "symbols": z.array(z.object({
                "symbol": z.string().describe('Symbol name.'),
                "markupBid": z.number().describe('Bid markup.'),
                "markupAsk": z.number().describe('Ask markup.')
            }).describe('Symbol-level configuration for gateway.')).describe('List of symbols assigned to this gateway.')
        }).optional().describe('Single gateway settings.')
    }).describe('Gateway configuration object.')).describe('List of configured gateways and their parameters.'),
    "feeders": z.array(z.object({
        "feeder": z.object({
            "name": z.string().describe('Feeder name.'),
            "enable": z.number().describe('Enable flag (1=enabled, 0=disabled).')
        }).optional().describe('Feeder configuration details.')
    }).describe('Feeder configuration entry.')).describe('List of market data feeders.'),
    "users": z.array(z.object({
        "user": z.object({
            "login": z.number().describe('User login ID.'),
            "group": z.string().describe('User group name.'),
            "password": z.string().describe('User password.'),
            "enable": z.number().describe('Enable flag (1=enabled, 0=disabled).'),
            "name": z.string().describe('Full name of the user.'),
            "country": z.string().describe('User country.'),
            "zipcode": z.string().describe('ZIP or postal code.'),
            "city": z.string().describe('City of residence.'),
            "address": z.string().describe('Street address.'),
            "phone": z.string().describe('Phone number.'),
            "email": z.string().describe('Email address.'),
            "balance": z.number().describe('Account balance.'),
            "credit": z.number().describe('Credit amount.'),
            "leverage": z.number().describe('Account leverage ratio.')
        }).optional().describe('User account data.')
    }).describe('User account configuration entry.')).describe('List of user account configurations.')
}).describe('Configuration schema for MT4\/MT5 trading server setup.')


/**
 * Verify that the service is available.
 * @summary Health check
 */
export const GetV1PingResponse = z.object({
    "status": z.string().optional()
})


/**
 * Retrieve service version
 * @summary Retrieve service version
 */
export const GetV1VersionResponse = z.object({
    "version": z.string().optional().describe('Service version'),
    "informationalVersion": z.string().optional().describe('Additional version information (e.g., build metadata)'),
    "time": z.string().describe('Timestamp when the version information was generated')
})


/**
 * @summary Get server performance metrics
 */
export const GetV1ServerPerformanceResponse = z.object({
    "cpu_usage": z.number().describe('Cpu usage'),
    "memory_usage": z.number().describe('Memory usage'),
    "uptime_sec": z.number().describe('Uptime')
})

// ===== Operations Map =====

export const operations = {} as const;

// ===== Testurio Service Type =====

/**
 * Schema-first (recommended, requires runtime validation support):
 *   new HttpProtocol({ schema: mTSchema })
 *
 * Current usage (explicit generic, no runtime validation):
 *   new HttpProtocol<MT>()
 */
export interface MT {

}

// ===== Type Helpers =====

export type MTOperations = typeof operations;
export type MTOperationId = keyof MT;
